#!/bin/bash
#
# flash-bootimage-switch-slot - Helper script to switch the active slot
# Copyright (C) 2021 Eugenio "g7" Paolantonio <me@medesimo.eu>
# Copyright (C) 2024 Deepak Kumar <notwho53@gmail.com>
# All rights reserved.
#
# Redistribution and use in source and binary forms, with or without
# modification, are permitted provided that the following conditions are met:
#    * Redistributions of source code must retain the above copyright
#      notice, this list of conditions and the following disclaimer.
#    * Redistributions in binary form must reproduce the above copyright
#      notice, this list of conditions and the following disclaimer in the
#      documentation and/or other materials provided with the distribution.
#    * Neither the name of the <organization> nor the
#      names of its contributors may be used to endorse or promote products
#      derived from this software without specific prior written permission.
#
# THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS "AS IS" AND
# ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE IMPLIED
# WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE ARE
# DISCLAIMED. IN NO EVENT SHALL <COPYRIGHT HOLDER> BE LIABLE FOR ANY
# DIRECT, INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES
# (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES;
# LOSS OF USE, DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER CAUSED AND
# ON ANY THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT LIABILITY, OR TORT
# (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT OF THE USE OF THIS
# SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.

set -e

FLASH_BOOTIMAGE_SWITCH_SLOT_FILE="/var/cache/flash-bootimage/flash-bootimage-switch-slot"

source /usr/share/flash-bootimage/common.sh

help() {
	cat <<EOF
${0} - switches the active slot

Usage: ${0}
EOF

}

[ -e "${FLASH_BOOTIMAGE_SWITCH_SLOT_FILE}" ] || error "Haven't been asked to switch the active slot!"

rm -f "${FLASH_BOOTIMAGE_SWITCH_SLOT_FILE}"

if [ -x "${PLYMOUTH}" ]; then
	plymouth_message "Please wait"
fi

/usr/bin/dd if=/dev/droidian/droidian-persistent of=/dev/disk/by-partlabel/boot bs=1M 
systemctl reboot
