name: Build Adaptation Package 

on:
  push:
    branches:
      - main
  workflow_dispatch:
  
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v4

    - name: GIT
      run: |
        git config --global user.name WHO53
        git config --global user.email notwho53@gmail.com

    - name: Set up QEMU
      run: docker run --rm --privileged multiarch/qemu-user-static --reset -p yes

    - name: Clone droidian-build-tools
      run: git clone https://github.com/droidian-releng/droidian-build-tools/ $HOME/droidian-build-tools

    - name: Create Template for Device
      run: |
        cd $HOME/droidian-build-tools/bin
        ./droidian-new-device -v lenovo -n akita -c arm64 -a 28 -r phone -d droidian
    
    - name: Build Deb Package
      run: |
        cd $HOME/droidian-build-tools/bin/droidian/lenovo/akita/packages/
        git clone https://github.com/WHO53/droidian-lenovo-akita temp-adaptation
        cd temp-adaptation
        bash $HOME/droidian-build-tools/bin/droidian-build-package
    
    - name: Upload Artifacts
      uses: actions/upload-artifact@v4
      with:
        name: adaptation
        path: ~/droidian-build-tools/bin/droidian/lenovo/akita/droidian/apt

  deploy:
    needs: build
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Download build artifacts
      uses: actions/download-artifact@v4
      with:
        name: adaptation
        path: ./adaptation

    - name: GIT
      run: |
        git config --global user.name WHO53
        git config --global user.email notwho53@gmail.com

    - name: Clone APT Repo
      run: |
        git clone https://${{ secrets.PAT }}@github.com/WHO53/apt.git
        cd apt/packages
        rm adaptation*
        cp ../../adaptation/*.deb .
        git add .
        git commit -m "Update adaptation packages"
        git push
      env:
        PAT: ${{ secrets.PAT }}
